### ISSUE TITLE
Readme shows unusable expansion variable '${project_folder}'

### ISSUE THREAD

**Issue by Reobos** [SublimeLinter/SublimeLinter-clang#2]
README is outdated - the ability to use the '${project_folder}' variable is deprecated but still mentioned in the settings. 

I made a pull request #1 to reflect the SublimeLinter expansion variable documentation and change from '${project_folder}' to '${project_path}' in the README.

**Comment by jfcherng** [comment]
`${project_folder}` could be for SL3 compatibility I guess. I am sure that there were codes that interpret `${project_folder}` like https://git.io/vxThI in `SublimeLinter-clang` because I cloned `SublimeLinter-clang` as `SublimeLinter-gcc` a year ago and I left that part untouched.

**Comment by Reobos** [comment]
It looks like SublimeLinter-clang removed that bit of code/functionality when upgrading to SublimeLinter 4. I think the changes you made to the linter in SublimeLinter-gcc can also benefit this linter (and SublimeLinter-avr-gcc which I maintain!). Thanks for keeping up on its development!

**Comment by Reobos** [comment]
See #1
