### ISSUE TITLE
Broken with newest SublimeLinter update

### ISSUE THREAD

**Issue by xolom** [SublimeLinter/SublimeLinter-clang#4]
It seems, that this plugin is broken with the newest sublimelinter update

**Comment by braver** [comment]
What's the "newest" for you exactly?

**Comment by xolom** [comment]
Version 4.3.0-pre.1

**Comment by braver** [comment]
From https://github.com/SublimeLinter/SublimeLinter/pull/1328/files

> Get the linter settings via 'get_linter_settings(linter, view)'

**Comment by kaste** [comment]
Nooo.

This linter claims stdout and stderr. To improve SL error handling we now have a standard callback if there is any output on stderr.

Either this linter always and only reports/uses stderr then it should define error_stream. If it really expects linter errors on both pipes, it must set on_stderr = None

**Comment by kaste** [comment]
get_linter_settings is a new API only if you don't have a linter instance yet. So we probably need to make that clearer in the changelog.

**Comment by kaste** [comment]
The general theme for SL4 and especially for 4.3 is to push all linter plugins to report hard errors e.g. config errors to the user.

**Comment by kaste** [comment]
@schreda I'm not using this linter. Does clang actually use stdout for anything useful or only stderr?

**Comment by kaste** [comment]
Please test PR at #6
